### PR TITLE
Handle destructive and lightning components

### PR DESCRIPTION
**Pull request by pyao-bwc**
We've had to perform manual steps when creating packages that are destructive or include Lightning Components:
- Per the [migration tool guide](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm), we have to include an empty package.xml in the same directory as destructiveChanges.xml
- As Bob Buzzard [documents](http://bobbuzzard.blogspot.com/2016/03/deploying-lightning-components-go-big.html), we have to include the entire Lightning Component bundle, even if only one file changes.

This change also updates the API version to 40 from 37, and handles file renaming in git version 2.14.2

### CODE REVIEW

**Comment by dlively1** [comment]
Thanks for the contribution @pyao-bwc. I'll check this out in the next few days. Apologies for the delay need to check my notification settings on personal repos.

**Comment by pyao-bwc** [comment]
Hey, no problem! Thanks for the tool, we love it and using it is a critical part of our process – not sure how others get by without it.

And this is my first public contribution… I’m open to feedback, or happy to have these changes live in my fork -

**Comment by seansoriano** [comment]
@dlively1 is this still currently in review?

**Comment by dlively1** [comment]
Hey, @pyao-bwc thanks for your work on this feature. I apologize for the extreme delay in reviewing this PR. I have been using this tool in production for quite some time but haven't had the need to make any updates until lately.

Looking to dust off the project and make a few improvements. I have moved the base branch to a `1.x`
which will include a few other minor enhancements.

**Comment by dlively1** [comment]
> @dlively1 is this still currently in review?

Yup. Just now got back around to this. Grouping this up with a few other changes coming out in [Version 1.0](https://github.com/dlively1/sf-packager/milestone/1)

**Pull request merged**
